site_name: Foliada cheatsheet
nav:
- Home: index.md
- Pezas:
  - Cantos:
    - Axudaime: pezas/cantos/pezas/axudaime.md
    - Os Bois: pezas/cantos/pezas/os_bois.md
    - Tiros: pezas/cantos/pezas/tiros.md
  - Muinheiras:
    - Bembibre: pezas/muinheiras/pezas/bembibre.md
    - Danza Das Pereiras: pezas/muinheiras/pezas/danza_das_pereiras.md
    - Esgos: pezas/muinheiras/pezas/esgos.md
    - Golpes: pezas/muinheiras/pezas/golpes.md
    - Linhares: pezas/muinheiras/pezas/linhares.md
    - Manolo: pezas/muinheiras/pezas/manolo.md
    - Pereira (Lero): pezas/muinheiras/pezas/pereira_(lero).md
    - Ribeirinha: pezas/muinheiras/pezas/ribeirinha.md
    - San Salvador: pezas/muinheiras/pezas/san_salvador.md
    - Seaia: pezas/muinheiras/pezas/seaia.md
    - Seaiaii: pezas/muinheiras/pezas/seaiaII.md
    - Zaragoza: pezas/muinheiras/pezas/zaragoza.md
  - Foliadas:
    - Rosinha: pezas/foliadas/pezas/rosinha.md
    - Route: pezas/foliadas/pezas/route.md
    - Zanfoga: pezas/foliadas/pezas/zanfoga.md
  - Maneos:
    - Abelenda: pezas/maneos/pezas/abelenda.md
    - Agoraque: pezas/maneos/pezas/agoraque.md
    - Bazar: pezas/maneos/pezas/bazar.md
    - Cabaleiros: pezas/maneos/pezas/cabaleiros.md
    - Imende: pezas/maneos/pezas/imende.md
    - Rececinde: pezas/maneos/pezas/rececinde.md
    - Silvan: pezas/maneos/pezas/silvan.md
  - Agarrados:
    - Alumeame: pezas/agarrados/pezas/alumeame.md
    - Lampai: pezas/agarrados/pezas/lampai.md
    - Montealegre: pezas/agarrados/pezas/montealegre.md
    - Monzo: pezas/agarrados/pezas/monzo.md
    - Seixedos: pezas/agarrados/pezas/seixedos.md
    - Xoane: pezas/agarrados/pezas/xoane.md
  - Xotas:
    - Barro: pezas/xotas/pezas/barro.md
    - Bazar: pezas/xotas/pezas/bazar.md
    - Caroi: pezas/xotas/pezas/caroi.md
    - Carolina: pezas/xotas/pezas/carolina.md
    - Ferrinhas: pezas/xotas/pezas/ferrinhas.md
    - Linhares: pezas/xotas/pezas/linhares.md
    - Linharesii: pezas/xotas/pezas/linharesII.md
    - Lira: pezas/xotas/pezas/lira.md
    - Luna: pezas/xotas/pezas/luna.md
    - Moscoso: pezas/xotas/pezas/moscoso.md
    - Moscosoii: pezas/xotas/pezas/moscosoii.md
    - Panaderas: pezas/xotas/pezas/panaderas.md
    - Rianxo: pezas/xotas/pezas/rianxo.md
    - Senhora: pezas/xotas/pezas/senhora.md
    - Xotaseaia: pezas/xotas/pezas/xotaseaia.md
theme:
  name: material
  language: gl
  features:
  - navigation.instant
  - navigation.tabs
  - search.suggest
  - search.highlight
  - search.share
  palette:
    primary: blue-grey
    accent: orange
  logo: images/logo.png
  favicon: images/favicon.ico
  font:
    text: Roboto
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/moronbandin
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/moronbandin
extra_css:
- assets/css/styles.css
plugins:
- search
