site_name: Foliada cheatsheet
nav:
  - Letras:
      - Abelenda: 'all/abelenda.md'
      - Axudaime: 'all/axudaime.md'
      - Bazar: 'all/bazar.md'
      - Maneo de Cabaleiros: 'all/cabaleiros.md'
      - Muiñeira de Esgos: 'all/esgos.md'
      - Xota de Corcubión: 'all/ferrinhas.md'
      - Lerole: 'all/lerole.md'
      - Xota de Liñares: 'all/linhares.md'
      - Aluméame luíña: 'all/luinha.md'
      - Muiñeira Maronda: 'all/maronda.md'
      - Rumba de Montealegre: 'all/montealegre.md'
      - Rumba de Monzo: 'all/rumba.md'
      - Regueifa de San Salvador de Pedreiro: 'all/sansalvador.md'
      - Maneo de Silván: 'all/silvan.md'
      - Canto, muiñeira e xota de Zanfoga: 'all/zanfoga.md'
      - Muiñeira de Veiga: all/zaragoza.md
      - Muiñeira de Liñares: all/m_linhares.md

theme:
  name: 'material'
  language: 'es'
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share  
  palette:
    primary: 'green'
    accent: 'orange'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  font:
    text: 'Roboto'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moronbandin
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moronbandin
plugins:
  - search      
